#!/bin/sh /etc/rc.common

START=96

USE_PROCD=1

start_service()
{
    procd_open_instance
    procd_set_param command udhcpd -f /etc/udhcpd.conf
    procd_set_param respawn 10 10 100
    procd_close_instance
}
